### ISSUE TITLE
Chrome extension on webstore is out of date

### ISSUE THREAD

**Issue by dcrousso** [oguzgelal/RedditPopup#2]
The extension on the webstore still shows as version 1.3.1.  Can you please update this as I would really like to use the plugin?

**Comment by oguzgelal** [comment]
Sorry about that been busy. I'll update today.

Oğuz Gelal
Özyeğin Üniversitesi

**Comment by oguzgelal** [comment]
@dcrousso Hello there. There seems to be a bug in your version, when you open the popup and close it, you cannot open a popup again, it instantly closes. I'll open an issue now. I'll fix it as soon as I can but if you fix it first, I'll then update the Chrome Store. Thanks for your contribution btw :+1:
