### ISSUE TITLE
When a a popup is opened and closed, another popup cannot be opened.

### ISSUE THREAD

**Issue by oguzgelal** [oguzgelal/RedditPopup#3]
Yeah, this has a self explanatory title. When a popup is opened and closed, the next one you'll open closes instantly. I suspected that it is because a duplicate click but I'm not sure.

**Comment by dcrousso** [comment]
I have opened another pull request ([#4](https://github.com/oguzgelal/RedditPopup/pull/4)) that contains the fix for this issue and another I found while fixing this one.

**Comment by oguzgelal** [comment]
@dcrousso Yup, now it seems to be working fine :) I merged and now I'll update the Chrome extension

**Comment by oguzgelal** [comment]
@dcrousso Uploaded to Chrome Store ^^
